Modify README.md Add support for script/allocate/deallocate With tests Signed-off-by: Jerome Hurstel <jerome.hurstel@atos.net>

diff --git a/test/aix_fake/nim b/test/aix_fake/nim
--- a/test/aix_fake/nim
+++ b/test/aix_fake/nim
@@ -11,7 +11,7 @@ fields['source']=''
 fields['packages']=''
 fields['comments']=''
 fields['lpp_source']=''
-
+fields['script']=''
 
 #===============================================
 # Usage
@@ -69,37 +69,52 @@ function run_action
     # NIM Define lpp_source
     if [ $action_type -eq 0 ]
     then
-		# lpp_source test value of 7100-02-02-1316-lpp_source should return an error although it exists in Ohai
-	    if [ "${fields['location']}" == "/sumatest/suma/error4/7100-02-02-1316-lpp_source" ]
-		then
-			echo "### NIM FAKE Define ERROR ###"
-			echo "0042-001 nim: processing error encountered on \"${fields['server']}\":" >&2
-			echo "   0042-001 m_mk_lpp_source: processing error encountered on \"${fields['server']}\":" >&2
-			echo "   0042-154 c_stat: the file or directory \"${fields['location']}\" does not exist" >&2
-			echo "" >&2
-			echo "" >&2
-			exit 1
-		else
+        # lpp_source test value of 7100-02-02-1316-lpp_source should return an error although it exists in Ohai
+        if [ "${fields['location']}" == "/sumatest/suma/error4/7100-02-02-1316-lpp_source" ]
+        then
+            echo "### NIM FAKE Define ERROR ###"
+            echo "0042-001 nim: processing error encountered on \"${fields['server']}\":" >&2
+            echo "   0042-001 m_mk_lpp_source: processing error encountered on \"${fields['server']}\":" >&2
+            echo "   0042-154 c_stat: the file or directory \"${fields['location']}\" does not exist" >&2
+            echo "" >&2
+            echo "" >&2
+            exit 1
+        else
             echo "### NIM FAKE Define ###"
-			echo "Preparing to copy install images (this will take several minutes)..."
-			echo ""
-			echo "Now checking for missing install images..."
-		fi
+            echo "Preparing to copy install images (this will take several minutes)..."
+            echo ""
+            echo "Now checking for missing install images..."
+        fi
     fi
 
     # NIM Customisation operation
     if [ $action_type -eq 1 ]
     then
-		# lpp_source test value of 7100-08-00-0000-lpp_source should return an error although it exists in Ohai
-	    if [ "${fields['lpp_source']}" == "7100-08-00-0000-lpp_source" ]
-		then
-			echo "### NIM FAKE ERROR when CUSTOM OPERATION on client $object_name with resource ${fields['lpp_source']} ###"
-			echo "0042-001 nim: processing error encountered on \"master\":" >&2
-			echo "" >&2
-			exit 1
-		else
-			echo "### NIM FAKE DONE CUSTOM OPERATION on client $object_name with resource ${fields['lpp_source']} ###"
-		fi
+        # lpp_source test value of 7100-08-00-0000-lpp_source should return an error although it exists in Ohai
+        if [ "${fields['lpp_source']}" == "7100-08-00-0000-lpp_source" ]
+        then
+            echo "### NIM FAKE ERROR when CUSTOM OPERATION on client $object_name with resource ${fields['lpp_source']} ###"
+            echo "0042-001 nim: processing error encountered on \"master\":" >&2
+            echo "" >&2
+            exit 1
+        elif [ ! -z "${fields['script']}" ]
+        then
+            echo "### NIM FAKE DONE CUSTOM OPERATION with script ${fields['script']} ###"
+        else
+            echo "### NIM FAKE DONE CUSTOM OPERATION on client $object_name with resource ${fields['lpp_source']} ###"
+        fi
+    fi
+
+    # NIM Allocate operation
+    if [ $action_type -eq 2 ]
+    then
+        echo "### NIM FAKE DONE ALLOCATE OPERATION ###"
+    fi
+
+    # NIM Deallocate operation
+    if [ $action_type -eq 3 ]
+    then
+        echo "### NIM FAKE DONE DEALLOCATE OPERATION ###"
     fi
 }
 
@@ -136,14 +151,8 @@ done
 shift $((OPTIND-1))
 object_name="$*"
 
-if [ ! -z "$operation"-a ! -z "$nimtype" ] 
+if [ ! -z "$operation" ] 
 then
-    echo "### NIM FAKE ###"
-    if [ ! -z $(echo $object_name | grep "error") ]
-    then
-        echo "-- Failure NIM --"
-        exit 1
-    fi
     if [ "$operation" == "define" -a "$nimtype" == "lpp_source" ]
     then
         run_action 0
@@ -154,7 +163,17 @@ then
         run_action 1
         exit 0
     fi
-    echo "#### BAD OPERATION & TYPE ($operation/$nimtype) ####"
+    if [ "$operation" == "allocate" ]
+    then
+        run_action 2
+        exit 0
+    fi
+    if [ "$operation" == "deallocate" ]
+    then
+        run_action 3
+        exit 0
+    fi
+    echo "#### BAD OPERATION ($operation) ####"
     exit 1
 fi
 
