fixes for Travis add nim tests and rakefile change fakes Signed-off-by: Jerome Hurstel <jerome.hurstel@atos.net>

diff --git a/test/aix_fake/nim b/test/aix_fake/nim
--- a/test/aix_fake/nim
+++ b/test/aix_fake/nim
@@ -60,22 +60,6 @@ usage:
 }
 
 #===============================================
-# error_managment
-#===============================================
-function error_managment
-{
-	error_message=""
-    if [ ! -z "$error_message" ]
-    then
-    	echo $error_message
-	    log_file="${fields['location']}/nim.error"
-	    echo "---- $(date) ----" >> $log_file
-    	echo $error_message >> $log_file
-    	echo "" >> $log_file
-    fi   
-}
-
-#===============================================
 # run_action
 #===============================================
 function run_action
@@ -85,24 +69,34 @@ function run_action
     # NIM Define lpp_source
     if [ $action_type -eq 0 ]
     then
-	    echo "Preparing to copy install images (this will take several minutes)..."
-	    echo ""
-	    echo "Now checking for missing install images..."
+	    if [ "${fields['location']}" == "" ]
+		then
+			echo "0042-001 nim: processing error encountered on \"${fields['server']}\":" >&2
+			echo "   0042-001 m_mk_lpp_source: processing error encountered on \"${fields['server']}\":" >&2
+			echo "   0042-154 c_stat: the file or directory \"${fields['location']}\" does not exist" >&2
+			echo "" >&2
+			echo "" >&2
+			exit 1
+		else
+			echo "Preparing to copy install images (this will take several minutes)..."
+			echo ""
+			echo "Now checking for missing install images..."
+		fi
     fi
 
     # NIM Customisation operation
     if [ $action_type -eq 1 ]
     then
-	    echo ""
+		# lpp_source test value of 7100-08-00-0000-lpp_source should return an error although it exists in Ohai
+	    if [ "${fields['lpp_source']}" == "7100-08-00-0000-lpp_source" ]
+		then
+			echo "0042-001 nim: processing error encountered on \"master\":" >&2
+			echo "" >&2
+			exit 1
+		else
+			echo ""
+		fi
     fi
-    log_file="${fields['location']}/nim.log"
-    echo "---- $(date) ----" >> $log_file
-    echo "\tname : $object_name" >> $log_file
-    for key in "${!fields[@]}"
-    do
-        echo "\t$key : ${fields[$key]}" >> $log_file
-    done
-    echo "" >> $log_file
 }
 
 #=====================================
@@ -112,16 +106,15 @@ while getopts "o:Ft:S:a:h" opt ; do
     case $opt in
     a) 
 IFS='=' read key value <<END
-	$OPTARG
+    $OPTARG
 END
-	   key=$(echo $key)
-	   if [ ! -z "$(echo ${!fields[@]} | grep $key)" ]
-	   then  
-			fields[$key]="$value"
+       key=$(echo $key)
+       if [ ! -z "$(echo ${!fields[@]} | grep $key)" ]
+       then
+            fields[$key]="$value"
        fi
        ;;
     o) operation=$OPTARG
-    
        ;;
     t) nimtype=$OPTARG
        ;;
@@ -138,27 +131,27 @@ END
 done
 shift $((OPTIND-1))
 object_name="$*"
- 
+
 if [ ! -z "$operation"-a ! -z "$nimtype" ] 
 then
-	echo "### NIM FAKE ###"
+    echo "### NIM FAKE ###"
     if [ ! -z $(echo $object_name | grep "error") ]
     then
-    	echo "-- Failure NIM --"
-		exit 1
-    fi	
-	if [ "$operation" == "define" -a "$nimtype" == "lpp_source" ]
-	then
-		run_action 0
-		exit 0
-	fi
-	if [ "$operation" == "cust" ]
-	then
-		run_action 1
-		exit 0
-	fi
-	echo "#### BAD OPERATION & TYPE ($operation/$nimtype) ####"
-	exit 1
+        echo "-- Failure NIM --"
+        exit 1
+    fi
+    if [ "$operation" == "define" -a "$nimtype" == "lpp_source" ]
+    then
+        run_action 0
+        exit 0
+    fi
+    if [ "$operation" == "cust" ]
+    then
+        run_action 1
+        exit 0
+    fi
+    echo "#### BAD OPERATION & TYPE ($operation/$nimtype) ####"
+    exit 1
 fi
 
 echo "#### NOT IMPLEMENTED ####"
