test improvement

diff --git a/test/aix_fake/suma b/test/aix_fake/suma
--- a/test/aix_fake/suma
+++ b/test/aix_fake/suma
@@ -48,25 +48,22 @@ Delete a SUMA task.
 function error_managment
 {
 	error_message=""
-    if [ ! -z $(echo "${fields['DisplayName']}" | grep "error") ]
+	display_name="${fields['DisplayName']}"
+    if [ ! -z $(echo $display_name | grep "error") ]
     then
-        if [ ! -z $(echo "${fields['DisplayName']}" | grep "BSO") ]
+        if [ ! -z $(echo $display_name | grep "BSO") ]
         then
-            error_message='
-CWPKI0022E: SSL HANDSHAKE FAILURE:  A signer with SubjectDN "CN=ASA Temporary Self Signed Certificate" was sent from target host:port "esupport.ibm.com:443".  The signer may need to be added to local trust store  "/var/ecc/data/TrustList.jks" located in SSL configuration alias "null" loaded from SSL configuration file "null".  The extended error message from the SSL handshake exception is: "PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target".
-
-CWPKI0040I: An SSL handshake failure occurred from a secure client.  The server's SSL signer has to be added to the client's trust store.  A retrieveSigners utility is provided to download signers from the server but requires administrative permission.  Check with your administrator to have this utility run to setup the secure environment before running the client.  Alternatively, the com.ibm.ssl.enableSignerExchangePrompt can be enabled in ssl.client.props for "DefaultSSLSettings" in order to allow acceptance of the signer during the connection attempt.
-'
+            error_message="\nCWPKI0022E: SSL HANDSHAKE FAILURE:  A signer with SubjectDN \"CN=ASA Temporary Self Signed Certificate\" was sent from target host:port "esupport.ibm.com:443".  The signer may need to be added to local trust store  "/var/ecc/data/TrustList.jks" located in SSL configuration alias "null" loaded from SSL configuration file "null".  The extended error message from the SSL handshake exception is: \"PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target\".\n\nCWPKI0040I: An SSL handshake failure occurred from a secure client.  The server's SSL signer has to be added to the client's trust store.  A retrieveSigners utility is provided to download signers from the server but requires administrative permission.  Check with your administrator to have this utility run to setup the secure environment before running the client.  Alternatively, the com.ibm.ssl.enableSignerExchangePrompt can be enabled in ssl.client.props for \"DefaultSSLSettings\" in order to allow acceptance of the signer during the connection attempt.\n"
         fi
-        error_message+="0500-013 Failed to retrieve list from fix server."
+    	error_message="${error_message}0500-013 Failed to retrieve list from fix server."
     fi
-    if [ ! -z $(echo "${fields['DisplayName']}" | grep "not entitled") ]
+    if [ ! -z $(echo $display_name | grep "not entitled") ]
     then
         error_message="0500-059 Entitlement is required to download.
 The system's serial number is not entitled.
 Please go to the Fix Central website to download fixes."
     fi
-    if [ ! -z $(echo "${fields['DisplayName']}" | grep "up-to-date") ]
+    if [ ! -z $(echo $display_name | grep "up-to-date") ]
     then
         error_message="0500-035 No fixes match your query."
     fi
@@ -81,6 +78,7 @@ Please go to the Fix Central website to download fixes."
 	    echo "---- $(date) ----" >> $log_file
     	echo $error_message >> $log_file
     	echo "" >> $log_file
+    	exit 1
     fi   
 }
 
@@ -104,8 +102,10 @@ function generate_bff
     fi
     if [ "${fields['RqType']}" != "Latest" ]
     then
-	    version_origin=$(echo "${fields['FilterML']}" | sed 's|-||g')'00'
+	    version_origin=$(echo "${fields['FilterML']}" | sed 's|-||g')
+	    [ $version_origin -le 999999 ] && version_origin=$version_origin'00' 
 	    version_target=$(echo "${fields['RqName']}" | sed 's|-||g')
+	    [ $version_target -le 999999 ] && version_target=$version_target'00'
 	    [ $version_origin -ge $version_target ] && nb=0
 	fi    
     let last_value=855000
@@ -171,7 +171,7 @@ function run_action
             fi
         fi
 	done
-    let size=$nb_download*1000
+    let size=$nb_download*1024*1024*1024
 	echo "Total bytes of updates downloaded: $size"
 	echo "Summary:"
 	echo "        $nb_download downloaded"
