Fake suma prints error to stderr BSO network and network test do the same Suma with target empty test do not generate an error

diff --git a/test/aix_fake/suma b/test/aix_fake/suma
--- a/test/aix_fake/suma
+++ b/test/aix_fake/suma
@@ -51,17 +51,11 @@ function error_managment
 	display_name="${fields['DisplayName']}"
     if [ ! -z $(echo $display_name | grep "error") ]
     then
-        if [ ! -z $(echo $display_name | grep "BSO") ]
-        then
-            error_message="\nCWPKI0022E: SSL HANDSHAKE FAILURE:  A signer with SubjectDN \"CN=ASA Temporary Self Signed Certificate\" was sent from target host:port "esupport.ibm.com:443".  The signer may need to be added to local trust store  "/var/ecc/data/TrustList.jks" located in SSL configuration alias "null" loaded from SSL configuration file "null".  The extended error message from the SSL handshake exception is: \"PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target\".\n\nCWPKI0040I: An SSL handshake failure occurred from a secure client.  The server's SSL signer has to be added to the client's trust store.  A retrieveSigners utility is provided to download signers from the server but requires administrative permission.  Check with your administrator to have this utility run to setup the secure environment before running the client.  Alternatively, the com.ibm.ssl.enableSignerExchangePrompt can be enabled in ssl.client.props for \"DefaultSSLSettings\" in order to allow acceptance of the signer during the connection attempt.\n"
-        fi
-    	error_message="${error_message}0500-013 Failed to retrieve list from fix server."
+   	    error_message="0500-013 Failed to retrieve list from fix server."
     fi
     if [ ! -z $(echo $display_name | grep "not entitled") ]
     then
-        error_message="0500-059 Entitlement is required to download.
-The system's serial number is not entitled.
-Please go to the Fix Central website to download fixes."
+        error_message="0500-059 Entitlement is required to download. The system's serial number is not entitled. Please go to the Fix Central website to download fixes."
     fi
     if [ ! -z $(echo $display_name | grep "up-to-date") ]
     then
@@ -73,7 +67,7 @@ Please go to the Fix Central website to download fixes."
     fi
     if [ ! -z "$error_message" ]
     then
-    	echo $error_message
+    	echo "$error_message"  >&2
 	    log_file="${fields['DLTarget']}/suma.error"
 	    echo "---- $(date) ----" >> $log_file
     	echo $error_message >> $log_file
@@ -233,7 +227,7 @@ then
         echo "${fields['DLTarget']} must be an existing absolute path."
         echo "OR"
         echo "${fields['DLTarget']} must be the name of a NIM lpp_source."
-        echo "0500-049 Task is not valid."
+        echo "0500-049 Task is not valid." >&2
     	exit 1
     fi
     if [ "${fields['Action']}" == 'Preview' ]
